#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Structural config only, not secrets — see host_config.env's own comment
# header and this repo's README for the two-tier split. This script has no
# idea how host_config.env got populated: a forker writes it by hand from
# .env.example; for this operator it's generated by
# dahome_private_config/estate/hosts/stack-launch.sh, which is the one place
# that repo's prefixed naming convention gets translated away. Either way
# this script only ever sees the bare contract: INFISICAL_API_URL,
# CORE_INFRA_PROJECT_ID.
set -a
source "${SCRIPT_DIR}/host_config.env"
set +a

# Bootstrap credential — the identity's own auth to Infisical (NOT in Git,
# lives only on this host, regenerated on rebuild).
source ~/.secrets/infisical.env

export INFISICAL_TOKEN
INFISICAL_TOKEN=$(infisical login \
  --method=universal-auth \
  --client-id="${VSCODEHOST_CLIENT_ID}" \
  --client-secret="${VSCODEHOST_CLIENT_SECRET}" \
  --domain="${INFISICAL_API_URL}" \
  --silent --plain)

# Captured into a variable (not eval'd directly from the substitution) so a
# failed export trips `set -e` instead of silently starting the container
# with an empty PASSWORD.
VSCODE_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${CORE_INFRA_PROJECT_ID}" \
  --env=prod \
  --path=/vscode/code-server/ \
  --format=dotenv-export)
eval "$VSCODE_SECRETS"

# The one alias mapping: this repo's contract calls it TOKEN_SECRET
# (generic-name convention — code-server has no account/username to pair
# it with); compose expects PASSWORD.
export PASSWORD="${TOKEN_SECRET}"

cd "${SCRIPT_DIR}"
exec docker compose up -d --build
